# Generated by Django 2.2.6 on 2019-10-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('chi_num', models.IntegerField(primary_key=True, serialize=False)),
                ('chi_name', models.CharField(max_length=30)),
                ('chi_gen', models.CharField(max_length=10)),
                ('chi_birth', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('hou_num', models.IntegerField(primary_key=True, serialize=False)),
                ('hou_img', models.ImageField(upload_to='')),
                ('hou_lan', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('per_num', models.IntegerField(primary_key=True, serialize=False)),
                ('per_img', models.ImageField(upload_to='')),
                ('per_lan', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_num', models.IntegerField(primary_key=True, serialize=False)),
                ('record_con', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_num', models.IntegerField(primary_key=True, serialize=False)),
                ('tree_img', models.ImageField(upload_to='')),
                ('tree_lan', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'tree',
            },
        ),
    ]
