# Generated by Django 2.2.6 on 2019-10-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
    ]
