# Generated by Django 2.2.6 on 2019-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_eng', models.CharField(max_length=50)),
                ('label_kr', models.CharField(max_length=50)),
                ('explaination', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
