# Generated by Django 2.2.6 on 2019-11-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20191104_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='explaination',
            new_name='content',
        ),
    ]
